Adding 3rd example to repo
terramate-io/terramate-examples pull request #12
Opened 2023-12-04 19:27 UTC by vtimd

This pull request will add the 3rd set of example code to the repo for the blog on how to use terraform outputs across stacks.

2023-12-04 21:38 UTC, soerenmartius requested changes
Please see the comments. Also too, did you test this code, does it actually run?

2023-12-04 21:38 UTC, soerenmartius commented on 03-terraform-outputs-across-stacks/stacks/EC2/config.tm.hcl
> +}
We should always add a "newline at the end of each file", hence the stop sign here.

Here's how to do that with vscode: https://stackoverflow.com/questions/44704968/visual-studio-code-insert-newline-at-the-end-of-files

And that's why: https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

2023-12-04 21:41 UTC, soerenmartius commented
@vtimd just tried the code locally, it unfortunately doesn't work (try run `terramate generate` to trigger the code generation)
<img width="1566" alt="Screenshot 2023-12-04 at 22 40 10" src="https://github.com/terramate-io/terramate-examples/assets/930643/35773d77-964c-4842-b00e-01fe50d3b7dd">

Keep in mind that the example we defined in last weeks session was never tested and was meant as an example for you how the final implementation could look like

2023-12-05 02:14 UTC, vtimd commented
This PR was just a placeholder for the file links. I didn’t test the code. I’m going to get it fixed in parallel while I write the blog. I just needed the GitHub links for the blog. I knew the code was wrong when I saved it in Code. It was all red 😂

2023-12-22 15:42 UTC, kkmlr commented on 03-terraform-outputs-across-stacks/stacks/EC2/config.tm.hcl
> +  "dependencies" = [
```suggestion
  dependencies = [
```

2023-12-22 15:44 UTC, kkmlr commented on 03-terraform-outputs-across-stacks/stacks/EC2/dependencies.tm.hcl
> +}
```suggestion
      }
    }
  }
}
```
fixes `An argument or block definition is required here.`

2023-12-22 16:01 UTC, kkmlr commented on 03-terraform-outputs-across-stacks/stacks/EC2/dependencies.tm.hcl
> +
```suggestion
    tm_dynamic "terraform_remote_state" {
      for_each = global.dependencies
      iterator = value
      labels   = ["vpc"]


```

2023-12-28 22:38 UTC, soerenmartius requested changes
left more comments in shortcut

2023-12-29 14:13 UTC, soerenmartius commented on 03-terraform-outputs-across-stacks/stacks/config.tm.hcl
> +  }
formatting issue (run `terramate fmt`)

2024-01-02 16:16 UTC, vtimd commented
Closing. Starting Fresh.

2024-01-02 16:16 UTC, closed without merging